######################################################################
# Automatically generated by qmake (2.01a) Sat May 21 21:37:39 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              inc \
              src \

INCLUDEPATH += . inc

# Input
HEADERS += inc/FFTW_solver.h
SOURCES += src/FFTW_solver.cpp \
           src/main.cpp \

LIBS    += -lfftw3
CONFIG  -= qt
